version: '3.8'

services:
  redis:
    container_name: redis
    platform: linux/amd64
    image: redis:7.0.0
    command: redis-server
    ports:
      - "6379:6379"
  app:
    container_name: news-app
    restart: always
    platform: linux/amd64
    depends_on:
      - redis
    image: osvaldomargato/redis-tutorial:1.0.0
    links:
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dockercompose